import cammyImage from './cammy-top.png'
import p1Image from './cammy-1p-image.png'
import p2Image from './cammy-2p-image.png'
import anyPunch from '../CommandImages/p-any-icon.png'
import lPunch from '../CommandImages/p-l-icon.png'
import mPunch from '../CommandImages/p-m-icon.png'
import hPunch from '../CommandImages/p-h-icon.png'
import anyKick from '../CommandImages/k-any-icon.png'
import lKick from '../CommandImages/k-l-icon.png'
import mKick from '../CommandImages/k-m-icon.png'
import hKick from '../CommandImages/k-h-icon.png'
import keyPlus from '../CommandImages/plus-icon.png'
import keyUp from '../CommandImages/up-icon.png'
import keyDown from '../CommandImages/down-icon.png'
import keyRight from '../CommandImages/right-icon.png'
import keyLeft from '../CommandImages/left-icon.png'
import keyDR from '../CommandImages/down-right-icon.png'
import keyDL from '../CommandImages/down-left-icon.png'
import keyNutral from '../CommandImages/nutral-icon.png'
import keyNext from '../CommandImages/key-next.png'
import cammyLPunch from './lPunch.gif'

export const cammyDetails = [{
  name:"CAMMY",
  strongpoints:["aaaaaaaaaa","bbbbbbbb","ccccccccc"],
  weakpoints:["ddddddddddd","eeeeeeeeee","fffffffffffff"],
  topImage:cammyImage,
  p1Image:p1Image,
  p2Image:p2Image,
}]

export const cammyMoves = [{
  type:"通常技",
  commands:[lPunch],
  movesName:"立ち弱P(フーリガンジャブ)",
  startup:4,
  active:"4-6",
  recovery:7,
  hit:5,
  block:-2,
  cancel:"〇",
  tips:["連打キャンセル対応"],
  hitboxImage:cammyLPunch,
}, {
  type:"通常技",
  commands:[lKick],
  movesName:"立ち弱K(フーリガンローキック)",
  startup:5,
  active:"5-7",
  recovery:10,
  hit:2,
  block:-3,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[mPunch],
  movesName:"立ち中P(フーリガンストレート)",
  startup:6,
  active:"6-9",
  recovery:13,
  hit:6,
  block:-1,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[mKick],
  movesName:"立ち中K(トゥースマッシュ)",
  startup:8,
  active:"8-10",
  recovery:18,
  hit:3,
  block:-4,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[hPunch],
  movesName:"立ち強P(スイングナックル)",
  startup:8,
  active:"8-10",
  recovery:20,
  hit:2,
  block:-3,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[hKick],
  movesName:"立ち強K(スティールスライサー)",
  startup:11,
  active:"11-13",
  recovery:21,
  hit:2,
  block:-4,
  cancel:"×",
  tips:["PC時吹き飛びダウン","空振り時硬直2F増加"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[keyDown, keyPlus, lPunch],
  movesName:"しゃがみ弱P(ラピッドショット)",
  startup:4,
  active:"4-5",
  recovery:8,
  hit:5,
  block:-2,
  cancel:"〇",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[keyDown, keyPlus, lKick],
  movesName:"しゃがみ弱K(スタンレイピア)",
  startup:5,
  active:"5-7",
  recovery:7,
  hit:3,
  block:-2,
  cancel:"×",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[keyDown, keyPlus, mPunch],
  movesName:"しゃがみ中P(ライトグレネード)",
  startup:7,
  active:"7-9",
  recovery:14,
  hit:5,
  block:-2,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[keyDown, keyPlus, mKick],
  movesName:"しゃがみ中K(トゥーバズソー)",
  startup:7,
  active:"7-9",
  recovery:14,
  hit:1,
  block:-5,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[keyDown, keyPlus, hPunch],
  movesName:"しゃがみ強P(トーピードーシェル)",
  startup:"10",
  active:"10-13",
  recovery:"15",
  hit:7,
  block:1,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands:[keyDown, keyPlus, hKick],
  movesName:"しゃがみ強K(グランドスイープ)",
  startup:9,
  active:"9-11",
  recovery:24,
  hit:"Down",
  block:-10,
  cancel:"×",
  tips:["地上ヒット時ハードノックダウン","C/PC時ダウン時間延長","空中ヒット時吹き飛びダウン"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyLeft,keyPlus,mPunch],
  movesName:"リフトアッパー",
  startup:5,
  active:"5-9",
  recovery:12,
  hit:4,
  block:-1,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands:[keyRight,keyPlus,hKick],
  movesName:"ディレイリーパー",
  startup:18,
  active:"18-20",
  recovery:25,
  hit:"Down",
  block:-12,
  cancel:"〇",
  tips:["PC時吹き飛び時間増加"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands:[keyLeft,keyPlus,hKick],
  movesName:"アサルトブレード",
  startup:9,
  active:"9-11",
  recovery:18,
  hit:"Down",
  block:-7,
  cancel:"×",
  tips:["ヒット時のみジャンプキャンセル可能"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands:[keyLeft,keyPlus,mPunch,hPunch],
  movesName:"リフトコンビネーション",
  startup:9,
  active:"9-11",
  recovery:23,
  hit:"Down",
  block:-12,
  cancel:"×",
  tips:["ヒット時のみジャンプキャンセル可能"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands:[hPunch,keyNext,hKick],
  movesName:"スイングコンビネーション",
  startup:13,
  active:"13-31",
  recovery:29,
  hit:"Down",
  block:-12,
  cancel:"〇",
  tips:["1段目のみ必殺技キャンセル可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown, keyDR, keyRight, keyPlus, lKick],
  movesName:"弱 スパイラルアロー",
  startup:9,
  active:"9-21",
  recovery:21,
  hit:"Down",
  block:-12,
  cancel:"×",
  tips:["9-24F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyDR, keyRight, keyPlus, mKick],
  movesName:"中 スパイラルアロー",
  startup:9,
  active:"9-23",
  recovery:21,
  hit:"Down",
  block:-14,
  cancel:"×",
  tips:["9-26F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyDR, keyRight, keyPlus, hKick],
  movesName:"強 スパイラルアロー",
  startup:15,
  active:"15-30",
  recovery:21,
  hit:"Down",
  block:-12,
  cancel:"SA3",
  tips:["18-33F 空中判定","16F以上ホールドすると性能変化"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyDR, keyRight, keyPlus, hKick],
  movesName:"[ホールド]強 スパイラルアロー",
  startup:27,
  active:"27-42",
  recovery:20,
  hit:"Down",
  block:-12,
  cancel:"SA3",
  tips:["30-45F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyDR, keyRight, keyPlus, anyKick, anyKick],
  movesName:"[OD]スパイラルアロー",
  startup:13,
  active:"13-28",
  recovery:20,
  hit:"Down",
  block:-14,
  cancel:"SA2",
  tips:["16-32F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight, keyDown, keyDR, keyPlus, lPunch],
  movesName:"弱 キャノンスパイク",
  startup:5,
  active:"5-16",
  recovery:"24+着地後16",
  hit:"Down",
  block:-36,
  cancel:"SA3",
  tips:["1-14F 空中判定の攻撃に対して無敵","7-40F 空中判定","持続の3F目移行は個別ダメージ(800)"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyRight, keyDown, keyDR, keyPlus, mPunch],
  movesName:"中 キャノンスパイク",
  startup:6,
  active:"6-17",
  recovery:"25+着地後16",
  hit:"Down",
  block:-36,
  cancel:"SA3",
  tips:["1-9F 空中判定の攻撃に対して無敵","8-42F 空中判定","持続の3F目移行は個別ダメージ(800)"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyRight, keyDown, keyDR, keyPlus, hPunch],
  movesName:"強 キャノンスパイク",
  startup:7,
  active:"7-18",
  recovery:"28+着地後16",
  hit:"Down",
  block:-36,
  cancel:"SA3",
  tips:["15F以上ホールドすると性能変化","1-8F 空中判定の攻撃に対して無敵","10-36F 空中判定","持続の3F目移行は個別ダメージ(800)"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyRight, keyDown, keyDR, keyPlus, hPunch],
  movesName:"[ホールド]強 キャノンスパイク",
  startup:24,
  active:"24-35",
  recovery:"29+着地後16",
  hit:"Down",
  block:-40,
  cancel:"SA3",
  tips:["1-7F 空中判定の攻撃に対して無敵","20-25F 完全無敵","26-64F 空中判定","持続の5F目移行は個別ダメージ(900)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight, keyDown, keyDR, keyPlus, anyPunch, anyPunch],
  movesName:"OD キャノンスパイク",
  startup:6,
  active:"6-17",
  recovery:"30+着地後16",
  hit:"Down",
  block:-40,
  cancel:"×",
  tips:["1-7F 完全無敵","8-47F 空中判定","持続の5F目移行は個別ダメージ(900)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown, keyDL, keyLeft, keyPlus, lPunch],
  movesName:"弱 アクセルスピンナックル",
  startup:21,
  active:"21-24",
  recovery:16,
  hit:2,
  block:-3,
  cancel:"SA3",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyDL, keyLeft, keyPlus, mPunch],
  movesName:"中 アクセルスピンナックル",
  startup:24,
  active:"24-27",
  recovery:16,
  hit:3,
  block:-2,
  cancel:"SA3",
  tips:["6-20F 飛び道具無敵"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyDL, keyLeft, keyPlus, hPunch],
  movesName:"強 アクセルスピンナックル",
  startup:28,
  active:"28-31",
  recovery:17,
  hit:5,
  block:3,
  cancel:"SA3",
  tips:["6-24F 飛び道具無敵"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyDL, keyLeft, keyPlus, anyPunch, anyPunch],
  movesName:"OD アクセルスピンナックル",
  startup:25,
  active:"25-28",
  recovery:17,
  hit:7,
  block:-2,
  cancel:"SA2",
  tips:["3-24F 飛び道具無敵","近距離で発動すると、相手の背後に回り込んでから攻撃を行う。その場合発生が3F遅くなる"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyKick],
  movesName:"キャノンストライク",
  movesCondition:"(前ジャンプ中に)",
  startup: 13,
  active:"13-23",
  recovery:"着地後12",
  hit:1,
  block:-5,
  cancel:"×",
  tips:["硬直差の数値は最速で発動した際の物"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyKick,anyKick],
  movesName:"OD キャノンストライク",
  movesCondition:"(前ジャンプ中に)",
  startup: 13,
  active:"13-22",
  recovery:"着地後12",
  hit:2,
  block:-2,
  cancel:"SA2",
  tips:["硬直差の数値は最速で発動した際の物"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown, keyDR, keyRight, keyPlus, anyPunch],
  movesName:"フーリガンコンビネーション",
  startup:"",
  active:"",
  recovery:"",
  hit:"",
  block:"",
  cancel:"×",
  tips:["21F~着地まで、レイザーエッジスライサーを除いた各種派生技でキャンセル可能","7F移行、空中判定"],
  hitboxImage:"",
},  {
  type:"必殺技",
  commands:[keyDown, keyDR, keyRight, keyPlus, hPunch],
  movesName:"[ホールド]フーリガンコンビネーション",
  startup:"",
  active:"",
  recovery:"",
  hit:"",
  block:"",
  cancel:"×",
  tips:["18F以上ホールドで性能変化","41F~着地まで、レイザーエッジスライサーを除いた各種派生技でキャンセル可能","27F移行、空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyDR, keyRight, keyPlus, anyPunch,anyPunch],
  movesName:"OD フーリガンコンビネーション",
  startup:"",
  active:"",
  recovery:"",
  hit:"",
  block:"",
  cancel:"×",
  tips:["21F~着地まで、ODレイザーエッジスライサーを除いた各種派生技でキャンセル可能","7F移行、空中判定"],
  hitboxImage:"",
},  {
  type:"必殺技",
  commands:[""],
  movesName:"レイザーエッジスライサー",
  movesCondition:"(フーリガンコンビネーション中に)入力なし",
  startup: 10,
  active:"10-18",
  recovery:13,
  hit:"Down",
  block:2,
  cancel:"SA3",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[""],
  movesName:"[ホールド]レイザーエッジスライサー",
  movesCondition:"(フーリガンコンビネーション中に)入力なし",
  startup: 10,
  active:"10-33",
  recovery:17,
  hit:"Down",
  block:2,
  cancel:"SA3",
  tips:["最終段のみSA3/CAでキャンセル可能"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[""],
  movesName:"OD レイザーエッジスライサー",
  movesCondition:"(フーリガンコンビネーション中に)入力なし",
  startup: 10,
  active:"10-33",
  recovery:17,
  hit:"Down",
  block:2,
  cancel:"SA2",
  tips:["最終段のみSA2/SA3/CAでキャンセル可能"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[anyKick],
  movesName:"(フーリガン)キャノンストライク",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: 13,
  active:"13-23",
  recovery:"着地後12",
  hit:"0~9",
  block:"-6~-3",
  cancel:"×",
  tips:["ヒット･ガードさせた高度によって硬直差が変化"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[anyKick],
  movesName:"[ホールド](フーリガン)キャノンストライク",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: 13,
  active:"13-22",
  recovery:"着地後12",
  hit:"4~9",
  block:"0~+5",
  cancel:"×",
  tips:["ヒット･ガードさせた高度によって硬直差が変化"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[anyKick],
  movesName:"(フーリガン)OD キャノンストライク",
  movesCondition:"(ODフーリガンコンビネーション中に)",
  startup: 13,
  active:"13-22",
  recovery:"着地後12",
  hit:"1~9",
  block:"-3~+5",
  cancel:"SA2",
  tips:["ヒット･ガードさせた高度によって硬直差が変化"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyPlus, anyKick],
  movesName:"リバースエッジ",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: 18,
  active:"18-21",
  recovery:"着地後13",
  hit:"+6~+9",
  block:"-4~-1",
  cancel:"×",
  hitboImage:"",
  tips: ["ヒット･ガードさせた高度によって硬直差が変化"],
}, {
  type:"必殺技",
  commands:[keyDown, keyPlus, anyKick],
  movesName:"[ホールド]リバースエッジ",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: 18,
  active:"18-39",
  recovery:"着地後13",
  hit:8,
  block:-2,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[keyDown, keyPlus, anyKick],
  movesName:"OD リバースエッジ",
  movesCondition:"(ODフーリガンコンビネーション中に)",
  startup: 18,
  active:"18-39",
  recovery:"着地後13",
  hit:8,
  block:-2,
  cancel:"SA2",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[lPunch,lKick],
  movesName:"フェイタルレッグツイスター",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: 10,
  active:"10-12",
  recovery:"着地後30",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[lPunch,lKick],
  movesName:"[ホールド]フェイタルレッグツイスター",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: 10,
  active:"10-12",
  recovery:"着地後30",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[lPunch,lKick],
  movesName:"OD フェイタルレッグツイスター",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: 10,
  active:"10-12",
  recovery:"着地後30",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[anyPunch],
  movesName:"サイレントステップ",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: "",
  active:"",
  recovery:"着地後10",
  hit:"",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[anyPunch],
  movesName:"[ホールド]サイレントステップ",
  movesCondition:"(フーリガンコンビネーション中に)",
  startup: "",
  active:"",
  recovery:"着地後10",
  hit:"",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands:[anyPunch],
  movesName:"OD サイレントステップ",
  movesCondition:"(ODフーリガンコンビネーション中に)",
  startup: "",
  active:"",
  recovery:"着地後10",
  hit:"",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown, keyDR, keyRight, keyDown, keyDR, keyRight, keyPlus, anyKick],
  movesName:"SA1 スピンドライブスマッシャー",
  startup:9,
  active:"9-19",
  recovery:38,
  hit:"Down",
  block:-24,
  cancel:"×",
  tips:["6段目以降は5段目ヒット時のみ派生"],
  hitboxImage:"",
}, {
  type:"スーパーアーツ",
  commands:[keyDown, keyDL, keyLeft, keyDown, keyDL, keyLeft, keyPlus, anyKick],
  movesName:"SA2 キラービースピン",
  startup:13,
  active:"13-21",
  recovery:37,
  hit:"Down",
  block:-24,
  cancel:"×",
  tips:["空中ヒット時は非ロック技に性能が変化する","ダメージ220×n(着地まで連続ヒット)"],
  hitboxImage:"",
}, {
  type:"スーパーアーツ",
  commands:[keyDown, keyDL, keyLeft, keyDown, keyDL, keyLeft, keyPlus, anyKick],
  movesName:"SA2 エアキラービースピン",
  movesCondition:"(前ジャンプ中に)",
  startup: 13,
  active:"13-着地まで",
  recovery:37,
  hit:"Down",
  block:-23,
  cancel:"×",
  tips:["空中ヒット時は非ロック技に性能が変化する","ダメージ220×n(着地まで連続ヒット)"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown, keyDR, keyRight, keyDown, keyDR, keyRight, keyPlus, anyPunch],
  movesName:"SA3 デルタレッドアサルト",
  movesCondition:"",
  startup:9,
  active:"9-23",
  recovery:"4+着地後34",
  hit:"Down",
  block:-33,
  cancel:"×",
  tips:["1-13F 完全無敵","9-27F 空中判定","最低保証ダメージ50%","C/PCで数値が変動しない","HP25%以下で性能変化"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown, keyDR, keyRight, keyDown, keyDR, keyRight, keyPlus, anyPunch],
  movesName:"CA デルタレッドアサルト",
  movesCondition:"(HP25%以下で)",
  startup:9,
  active:"9-23",
  recovery:"4+着地後34",
  hit:"Down",
  block:-33,
  cancel:"×",
  tips:["1-13F 完全無敵","9-27F 空中判定","最低保証ダメージ50%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"投げ",
  commands:[keyNutral, keyPlus, lPunch, lKick],
  movesName:"ラフランディング",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:23,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"投げ",
  commands:[keyLeft, keyPlus, lPunch, lKick],
  movesName:"デルタスルー",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:23,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"投げ",
  commands:[keyUp, keyPlus, lPunch, lKick],
  movesName:"レッグシザースチョーク",
  movesCondition:"(ジャンプ中に)",
  startup: 5,
  active:"5-7",
  recovery:"着地後3",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}]