import manonImage from './manon-top.png'
import p1Image from './manon-1p-image.png'
import p2Image from './manon-2p-image.png'
import anyPunch from '../CommandImages/p-any-icon.png'
import lPunch from '../CommandImages/p-l-icon.png'
import mPunch from '../CommandImages/p-m-icon.png'
import hPunch from '../CommandImages/p-h-icon.png'
import anyKick from '../CommandImages/k-any-icon.png'
import lKick from '../CommandImages/k-l-icon.png'
import mKick from '../CommandImages/k-m-icon.png'
import hKick from '../CommandImages/k-h-icon.png'
import keyPlus from '../CommandImages/plus-icon.png'
import keyDown from '../CommandImages/down-icon.png'
import keyRight from '../CommandImages/right-icon.png'
import keyLeft from '../CommandImages/left-icon.png'
import keyDR from '../CommandImages/down-right-icon.png'
import keyDL from '../CommandImages/down-left-icon.png'
import keyNutral from '../CommandImages/nutral-icon.png'
import keyNext from '../CommandImages/key-next.png'
import keyOr from '../CommandImages/or-icon.png'


export const manonDetails = [{
  name:"MANON",
  strongpoints:["aaaaa","bbbbb","ccccc"],
  weakpoints:["ddddd","eeeee","fffff"],
  topImage:manonImage,
  p1Image:p1Image,
  p2Image:p2Image,
}]

export const manonMoves = [{
  type:"通常技",
  commands:[lPunch],
  movesName:"立ち弱P(ハジメ)",
  movesCondition:"",
  startup:4,
  active:"4-6",
  recovery:10,
  hit:4,
  block:-1,
  cancel:"〇",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[lKick],
  movesName:"立ち弱K(タンジュ)",
  movesCondition:"",
  startup:5,
  active:"5-6",
  recovery:12,
  hit:2,
  block:-2,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[mPunch],
  movesName:"立ち中P(ツリテ)",
  movesCondition:"",
  startup:7,
  active:"7-10",
  recovery:14,
  hit:2,
  block:-2,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[mKick],
  movesName:"立ち中K(ラ･シェーヌ)",
  movesCondition:"",
  startup:10,
  active:"10-12",
  recovery:18,
  hit:-2,
  block:-5,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[hPunch],
  movesName:"立ち強P(ランドリ)",
  movesCondition:"",
  startup:10,
  active:"10-13",
  recovery:20,
  hit:0,
  block:-3,
  cancel:"SA",
  tips:["空中ヒット時吹き飛びダウン"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[hKick],
  movesName:"立ち強K(ピエ･ドンジュ)",
  movesCondition:"",
  startup:15,
  active:"15-17",
  recovery:26,
  hit:-2,
  block:-6,
  cancel:"×",
  tips:["地上PC時+17F","空中PC時吹き飛びダウン"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,lPunch],
  movesName:"しゃがみ弱P(ソデキリ)",
  movesCondition:"",
  startup:4,
  active:"4-5",
  recovery:11,
  hit:2,
  block:-2,
  cancel:"〇",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,lKick],
  movesName:"しゃがみ弱K(シーニュ･ナジェ)",
  movesCondition:"",
  startup:5,
  active:"5-6",
  recovery:13,
  hit:-1,
  block:-5,
  cancel:"×",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,mPunch],
  movesName:"しゃがみ中P(ヒキテ)",
  movesCondition:"",
  startup:7,
  active:"7-9",
  recovery:11,
  hit:6,
  block:-1,
  cancel:"〇",
  tips:["空振り時硬直2F増加"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,mKick],
  movesName:"しゃがみ中K(ストゥニュー)",
  movesCondition:"",
  startup:8,
  active:"8-11",
  recovery:16,
  hit:2,
  block:-2,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,hPunch],
  movesName:"しゃがみ強P(ヴィクトワール･ポーム)",
  movesCondition:"",
  startup:10,
  active:"10-14",
  recovery:21,
  hit:-2,
  block:-8,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,hKick],
  movesName:"しゃがみ強K(クロワゼ)",
  movesCondition:"",
  startup:11,
  active:"11-12",
  recovery:27,
  hit:"Down",
  block:-12,
  cancel:"×",
  tips:["C/PC時ダウン時間延長"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyLeft,keyPlus,hPunch],
  movesName:"レべランス",
  movesCondition:"",
  startup:8,
  active:"8-13",
  recovery:17,
  hit:3,
  block:-3,
  cancel:"〇",
  tips:["空中ヒット時吹き飛びダウン"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyDR,keyPlus,hKick],
  movesName:"トモエ･デリエール",
  movesCondition:"",
  startup:11,
  active:"11-19",
  recovery:32,
  hit:26,
  block:-23,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[mPunch,keyNext,mKick],
  movesName:"ア･テール",
  movesCondition:"",
  startup:10,
  active:"10-11",
  recovery:17,
  hit:2,
  block:-5,
  cancel:"×",
  tips:["空中ヒット時吹き飛びダウン"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyLeft,keyPlus,mKick],
  movesName:"アン･オー(1段目)",
  movesCondition:"",
  startup:10,
  active:"10-13",
  recovery:19,
  hit:-1,
  block:-3,
  cancel:"×",
  tips:["空中ヒット時吹き飛びダウン"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[mKick],
  movesName:"アン･オー(2段目)",
  movesCondition:"(アン･オー1段目後に)",
  startup:14,
  active:"14-20",
  recovery:21,
  hit:-3,
  block:-11,
  cancel:"〇",
  tips:["空中ヒット時吹き飛びダウン"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[hPunch,keyNext,hPunch],
  movesName:"タン･リエ",
  movesCondition:"",
  startup:5,
  active:"5-6",
  recovery:20,
  hit:1,
  block:-10,
  cancel:"×",
  tips:["ガード時硬直2F増加"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyDown,keyPlus,hPunch,keyNext,hPunch],
  movesName:"アロンジェ",
  movesCondition:"",
  startup:4,
  active:"4-7",
  recovery:26,
  hit:1,
  block:-10,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,lPunch],
  movesName:"弱 マネージュ･ドレ",
  movesCondition:"",
  startup:10,
  active:"10-11",
  recovery:49,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["ヒット時にメダルLvが1上昇","メダルLv1 2000(2300)","メダルLv2 2300(2645)","メダルLv3 2700(3105)","メダルLv4 3000(3450)","メダルLv5 3700(4255)","()内はパニッシュカウンター時のダメージ"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,mPunch],
  movesName:"中 マネージュ･ドレ",
  movesCondition:"",
  startup:8,
  active:"8-9",
  recovery:51,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["ヒット時にメダルLvが1上昇","メダルLv1 2000(2300)","メダルLv2 2300(2645)","メダルLv3 2700(3105)","メダルLv4 3000(3450)","メダルLv5 3700(4255)","()内はパニッシュカウンター時のダメージ"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,hPunch],
  movesName:"強 マネージュ･ドレ",
  movesCondition:"",
  startup:5,
  active:"5-6",
  recovery:54,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["ヒット時にメダルLvが1上昇","メダルLv1 2000(2300)","メダルLv2 2300(2645)","メダルLv3 2700(3105)","メダルLv4 3000(3450)","メダルLv5 3700(4255)","()内はパニッシュカウンター時のダメージ"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,anyPunch,anyPunch],
  movesName:"OD マネージュ･ドレ",
  movesCondition:"",
  startup:8,
  active:"8-9",
  recovery:51,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["ヒット時にメダルLvが1上昇","メダルLv1 2000(2300)","メダルLv2 2300(2645)","メダルLv3 2700(3105)","メダルLv4 3000(3450)","メダルLv5 3700(4255)","()内はパニッシュカウンター時のダメージ"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,lKick],
  movesName:"弱 ロン･ポワン",
  movesCondition:"",
  startup:9,
  active:"9-15",
  recovery:29,
  hit:"Down",
  block:-15,
  cancel:"SA3",
  tips:["5-15F 上半身のみ空中判定の攻撃に対して無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,mKick],
  movesName:"中 ロン･ポワン",
  movesCondition:"",
  startup:11,
  active:"11-19",
  recovery:27,
  hit:"Down",
  block:-14,
  cancel:"SA3",
  tips:["7-19F 上半身のみ空中判定の攻撃に対して無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,hKick],
  movesName:"強 ロン･ポワン",
  movesCondition:"",
  startup:14,
  active:"14-22",
  recovery:24,
  hit:"Down",
  block:-11,
  cancel:"SA3",
  tips:["9-22F 上半身のみ空中判定の攻撃に対して無敵","44-46F ヒット、ガード、アーマーヒット時に、必殺技、SAキャンセル可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,anyKick,anyKick],
  movesName:"OD ロン･ポワン",
  movesCondition:"",
  startup:9,
  active:"9-15",
  recovery:29,
  hit:"Down",
  block:-15,
  cancel:"SA3",
  tips:["4-16F 空中判定の攻撃に対して無敵","41-46F ヒット、ガード、アーマーヒット時に、必殺技、SAキャンセル可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,lKick],
  movesName:"弱 デガジェ",
  movesCondition:"",
  startup:16,
  active:"16-31",
  recovery:36,
  hit:"Down",
  block:-24,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,mKick],
  movesName:"中 デガジェ",
  movesCondition:"",
  startup:16,
  active:"16-39",
  recovery:22,
  hit:"Down",
  block:-13,
  cancel:"×",
  tips:["15-39F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,hKick],
  movesName:"強 デガジェ",
  movesCondition:"",
  startup:20,
  active:"20-22",
  recovery:24,
  hit:"Down",
  block:-9,
  cancel:"×",
  tips:["9-19F 足元無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyKick,anyKick],
  movesName:"OD デガジェ",
  movesCondition:"",
  startup:22,
  active:"22-24",
  recovery:22,
  hit:"Down",
  block:-3,
  cancel:"×",
  tips:["11-24F 足元無敵、投げ無敵","9-21F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,lPunch],
  movesName:"弱 ランヴェルセ",
  movesCondition:"",
  startup:22,
  active:"22-23",
  recovery:37,
  hit:"Down",
  block:-23,
  cancel:"SA3",
  tips:["3-21F 飛び道具に対して無敵","ボタンホールドでフェイントに派生(全体33F)","ヒット時にメダルLvが1上昇","メダルLv1 1350(1360)","メダルLv2 1500(1510)","メダルLv3 1650(1660)","メダルLv4 1800(1810)","メダルLv5 1950(1960)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,mPunch],
  movesName:"中 ランヴェルセ",
  movesCondition:"",
  startup:25,
  active:"25-26",
  recovery:34,
  hit:"Down",
  block:-20,
  cancel:"SA3",
  tips:["3-24F 飛び道具に対して無敵","ボタンホールドでフェイントに派生(全体34F)","ヒット時にメダルLvが1上昇","メダルLv1 1400(1420)","メダルLv2 1550(1570)","メダルLv3 1700(1720)","メダルLv4 1850(1870)","メダルLv5 2000(2020)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,hPunch],
  movesName:"強 ランヴェルセ",
  movesCondition:"",
  startup:29,
  active:"29-30",
  recovery:30,
  hit:"Down",
  block:-16,
  cancel:"SA3",
  tips:["3-28F 飛び道具に対して無敵","ボタンホールドでフェイントに派生(全体35F)","ヒット時にメダルLvが1上昇","メダルLv1 1500(1540)","メダルLv2 1650(1690)","メダルLv3 1800(1840)","メダルLv4 1950(1990)","メダルLv5 2100(2140)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,anyPunch,anyPunch],
  movesName:"OD ランヴェルセ",
  movesCondition:"",
  startup:25,
  active:"25-26",
  recovery:34,
  hit:"Down",
  block:-20,
  cancel:"×",
  tips:["3-26F 膝から上打撃に対して無敵","3-26F 飛び道具に対して無敵","ボタンホールドでフェイントに派生(全体34F)","ヒット時にメダルLvが1上昇","メダルLv1 1500(1540)","メダルLv2 1650(1690)","メダルLv3 1800(1840)","メダルLv4 1950(1990)","メダルLv5 2100(2140)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[anyKick],
  movesName:"グラン･フェッテ",
  movesCondition:"(ランヴェルセ中に)",
  startup:11,
  active:"11-16",
  recovery:22,
  hit:"Down",
  block:-5,
  cancel:"SA3",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[anyKick],
  movesName:"OD グラン･フェッテ",
  movesCondition:"(ランヴェルセ中に)",
  startup:11,
  active:"11-16",
  recovery:22,
  hit:"Down",
  block:-12,
  cancel:"SA2",
  tips:[""],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyKick],
  movesName:"SA1 アラベスク",
  movesCondition:"",
  startup:10,
  active:"10-13",
  recovery:65,
  hit:"Down",
  block:-49,
  cancel:"×",
  tips:["1-13F 打撃・投げに対して無敵","最低保障ダメージ30%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDL,keyLeft,keyDown,keyDL,keyLeft],
  movesName:"SA2 エトワール",
  movesCondition:"",
  startup:7,
  active:"7-80",
  recovery:"38+着地後34",
  hit:"Down",
  block:-61,
  cancel:"×",
  tips:["1-9F 完全無敵","21-36F、68-118F 空中判定","最低保障ダメージ40%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyPunch],
  movesName:"SA3 パ･ド･ドゥ",
  movesCondition:"",
  startup:7,
  active:"7-8",
  recovery:72,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["1-8F 完全無敵","最低保障ダメージ50%","C/PCで数値が変動しない","立ち強P、ロン・ポワンからキャンセル時のみ15%","HP25%以下で性能変化"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyPunch],
  movesName:"CA パ･ド･ドゥ",
  movesCondition:"",
  startup:7,
  active:"7-8",
  recovery:72,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["1-8F 完全無敵","最低保障ダメージ50%","C/PCで数値が変動しない","立ち強P、ロン・ポワンからキャンセル時のみ15%"],
  hitboxImage:"",
},{
  type:"投げ",
  commands:[keyNutral,keyOr,keyRight,keyPlus,lPunch,lKick],
  movesName:"オーウチガリ",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:23,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"投げ",
  commands:[keyLeft,keyPlus,lPunch,lKick],
  movesName:"ウチマタ",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:23,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},]