import lilyImage from './lily-top.png'
import p1Image from './lily-1p-image.png'
import p2Image from './lily-2p-image.png'
import anyPunch from '../CommandImages/p-any-icon.png'
import lPunch from '../CommandImages/p-l-icon.png'
import mPunch from '../CommandImages/p-m-icon.png'
import hPunch from '../CommandImages/p-h-icon.png'
import anyKick from '../CommandImages/k-any-icon.png'
import lKick from '../CommandImages/k-l-icon.png'
import mKick from '../CommandImages/k-m-icon.png'
import hKick from '../CommandImages/k-h-icon.png'
import keyPlus from '../CommandImages/plus-icon.png'
import keyDown from '../CommandImages/down-icon.png'
import keyRight from '../CommandImages/right-icon.png'
import keyLeft from '../CommandImages/left-icon.png'
import keyDR from '../CommandImages/down-right-icon.png'
import keyDL from '../CommandImages/down-left-icon.png'
import keyNutral from '../CommandImages/nutral-icon.png'
import keyNext from '../CommandImages/key-next.png'
import keyCircle from '../CommandImages/circle-icon.png'
import lilyLPunch from './lPunch.gif'

export const lilyDetails:{
  name:string;
  strongpoints:string[];
  weakpoints:string[];
  topImage:string;
  p1Image:string;
  p2Image:string;
} = {
  name:"LILY",
  strongpoints:["aaaaa","bbbbb","ccccc"],
  weakpoints:["ddddd","eeeee","fffff"],
  topImage:lilyImage,
  p1Image:p1Image,
  p2Image:p2Image,
}

export const lilyMoves:{
  [key:string]: string|string[]|number|number[],
  type:string
  commands:string[]
  movesName:string
  movesCondition:string
  startup:any
  active:any
  recovery:any
  hit:any
  block:any
  cancel:any
  tips:string[]
  hitboxImage:string 
}[] = [{
  type:"通常技",
  commands: [lPunch],
  movesName: "立ち弱P(コンドルビーク)",
  movesCondition:"",
  startup: 6,
  active: "6-8",
  recovery: 8,
  hit: 6,
  block: -1,
  cancel: "〇",
  tips: ["連打キャンセル可能"],
  hitboxImage:lilyLPunch,
}, {
  type:"通常技",
  commands: [lKick],
  movesName: "立ち弱K(ストマックプレスキック)",
  movesCondition:"",
  startup: 4,
  active: "4-6",
  recovery: 12,
  hit: 1,
  block: -4,
  cancel: "〇",
  tips: ["連打キャンセル対応"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [mPunch],
  movesName: "立ち中P(タタンカホーン)",
  movesCondition:"",
  startup: 9,
  active: "9-12",
  recovery: 17,
  hit: 1,
  block: -1,
  cancel: "×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [mKick],
  movesName: "立ち中K(ロンリーキック)",
  movesCondition:"",
  startup: 7,
  active: "7-9",
  recovery: 15,
  hit: 2,
  block: -1,
  cancel: "〇",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [hPunch],
  movesName: "立ち強P(メキシカンクロスホーン)",
  movesCondition:"",
  startup: 11,
  active: "11-13",
  recovery: 22,
  hit: 0,
  block: -5,
  cancel: "〇",
  tips:["地上PC時膝崩れ","空中PC時吹き飛びダウン"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [hKick],
  movesName: "立ち強K(ヘビートラースキック)",
  movesCondition:"",
  startup: 14,
  active: "14-17",
  recovery: 21,
  hit: 1,
  block: -5,
  cancel: "×",
  tips:["PC時吹き飛びダウン"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [keyDown, keyPlus, lPunch],
  movesName: "しゃがみ弱P(リリーショット)",
  movesCondition:"",
  startup: 6,
  active: "6-8",
  recovery: 8,
  hit: 5,
  block: -1,
  cancel: "〇",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [keyDown, keyPlus, lKick],
  movesName: "しゃがみ弱K(ロープレスキック)",
  movesCondition:"",
  startup: 5,
  active: "5-6",
  recovery: 12,
  hit: 2,
  block: -2,
  cancel: "×",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [keyDown, keyPlus, mPunch],
  movesName: "しゃがみ中P(ホーリーアース)",
  movesCondition:"",
  startup: 8,
  active: "8-10",
  recovery: 18,
  hit: 1,
  block: -3,
  cancel: "SA",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [keyDown, keyPlus, mKick],
  movesName: "しゃがみ中K(ヒールスライドキック)",
  movesCondition:"",
  startup: 10,
  active: "10-12",
  recovery: 18,
  hit: 1,
  block: -5,
  cancel: "〇",
  tips:[""],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [keyDown, keyPlus, hPunch],
  movesName: "しゃがみ強P(ハンマーアクス)",
  movesCondition:"",
  startup: 10,
  active: "10-15",
  recovery: 22,
  hit: 0,
  block: -2,
  cancel: "〇",
  tips:["空中C/PC時吹き飛びダウン"],
  hitboxImage:"",
}, {
  type:"通常技",
  commands: [keyDown, keyPlus, hKick],
  movesName: "しゃがみ強K(スコールキック)",
  movesCondition:"",
  startup: 11,
  active: "11-20",
  recovery: 24,
  hit: "Down",
  block: -12,
  cancel: "×",
  tips:["C/PC時ダウン時間延長"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands: [keyDR,keyPlus,hPunch],
  movesName: "スラストリッジ",
  movesCondition:"",
  startup: 25,
  active: "25-27",
  recovery: 18,
  hit: 2,
  block: -3,
  cancel: "〇",
  tips:["5-19F足元無敵","強制しゃがみ効果","空中ヒット時叩きつけダウン"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands: [keyRight,keyPlus,hKick],
  movesName: "ボーンブレイク",
  movesCondition:"",
  startup: 14,
  active: "14-17",
  recovery: 18,
  hit: 5,
  block: -2,
  cancel: "〇",
  tips:[""],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands: [keyDown,keyPlus,hPunch],
  movesName: "グレートスピン",
  movesCondition:"(ジャンプ中に)",
  startup: 9,
  active: "9-19",
  recovery: "着地後3",
  hit: "",
  block: "",
  cancel: "×",
  tips:["めくり性能"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands: [mPunch,keyNext,mPunch],
  movesName: "ダブルアロー",
  movesCondition:"(ジャンプ中に)",
  startup: 10,
  active: "10-12",
  recovery: "着地後3",
  hit: "Down",
  block: -12,
  cancel: "SA2",
  tips:["空中ヒット時吹き飛びダウン","SA2 スカイサンダーバードでのみキャンセル可能"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands: [keyRight,keyPlus,hPunch],
  movesName: "デザートストーム(1段目)",
  movesCondition:"",
  startup: 18,
  active: "18-19",
  recovery: 24,
  hit: 1,
  block: -5,
  cancel: "〇",
  tips:["空中ヒット時吹き飛びダウン"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands: [keyRight,keyPlus,hPunch,keyNext,hPunch],
  movesName: "デザートストーム(2段目)",
  movesCondition:"",
  startup: 20,
  active: "20-21",
  recovery: 27,
  hit: 0,
  block: -9,
  cancel: "×",
  tips:["空中ヒット時吹き飛びダウン"],
  hitboxImage:"",
}, {
  type:"特殊技",
  commands: [keyRight,keyPlus,hPunch,keyNext,hPunch,keyNext,hPunch],
  movesName: "デザートストーム(3段目)",
  movesCondition:"",
  startup: 20,
  active: "20-24",
  recovery: 42,
  hit: "Down",
  block: -26,
  cancel: "×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"必殺技",  
  commands: [keyDown, keyDL, keyLeft, keyPlus, lPunch],
    movesName: "弱 コンドルウィンド",
    movesCondition:"",
    startup: "",
    active: "",
    recovery: "全体47",
    hit: "",
    block: "",
    cancel: "×",
    tips:["最速でボタンを離した場合46F目で風纏いを1つストック","ボタンホールド時71F目で2つ目、91F目で3つ目をストック","次回発動するコンドルスパイア、トマホークバスター、コンドルダイブ、サンダーバード、スカイサンダーバードの性質変化"],
    hitboxImage:"",
  }, {
    type:"必殺技",
    commands: [keyDown, keyDL, keyLeft, keyPlus, mPunch],
    movesName: "中 コンドルウィンド",
    movesCondition:"",
    startup: 23,
    active: "23-26",
    recovery: 25,
    hit: "Down",
    block: -8,
    cancel: "SA3",
    tips:["発動から45F目までにボタンを離した場合、攻撃持続1F目で風纏いをストック","ボタンホールド時46F目で1つ目、71F目で2つ目、91F目で3つ目をストック","次回発動するコンドルスパイア、トマホークバスター、コンドルダイブ、サンダーバード、スカイサンダーバードの性質変化","空中ヒット時吹き飛びダウン"],
    hitboxImage:"",
  }, {
    type:"必殺技",
    commands: [keyDown, keyDL, keyLeft, keyPlus, hPunch],
    movesName: "強 コンドルウィンド",
    movesCondition:"",
    startup: 25,
    active: "25-28",
    recovery: 25,
    hit: "Down",
    block: -8,
    cancel: "SA3",
    tips:["発動から45F目までにボタンを離した場合、攻撃持続1F目で風纏いをストック","ボタンホールド時46F目で1つ目、71F目で2つ目、91F目で3つ目をストック","次回発動するコンドルスパイア、トマホークバスター、コンドルダイブ、サンダーバード、スカイサンダーバードの性質変化"],
    hitboxImage:"",
  }, {
    type:"必殺技",
    commands: [keyDown, keyDL, keyLeft, keyPlus, anyPunch, anyPunch],
    movesName: "OD コンドルウィンド",
    movesCondition:"",
    startup: 21,
    active: "21-24",
    recovery: 23,
    hit: "Down",
    block: -5,
    cancel: "SA2",
    tips:["発動から25F目までにボタンを離した場合、攻撃持続1F目で風纏いをストック","ボタンホールド時は38F目でストック、全体40F","次回発動するコンドルスパイア、トマホークバスター、コンドルダイブ、サンダーバード、スカイサンダーバードの性質変化"],
    hitboxImage:"",
  },{
    type:"必殺技",
    commands: [keyDown, keyDR, keyRight, keyPlus, lKick],
    movesName: "弱 コンドルスパイア",
    movesCondition:"",
    startup: 17,
    active: "17-29",
    recovery: 16,
    hit: "Down",
    block: -8,
    cancel: "×",
    tips:["8-30F 空中判定"],
    hitboxImage:"",
  }, {
    type:"必殺技",
    commands: [keyDown, keyDR, keyRight, keyPlus, mKick],
    movesName: "中 コンドルスパイア",
    movesCondition:"",
    startup: 21,
    active: "21-33",
    recovery: 16,
    hit: "Down",
    block: -8,
    cancel: "×",
    tips:["9-35F 空中判定"],
    hitboxImage:"",
  }, {
    type:"必殺技",
    commands: [keyDown, keyDR, keyRight, keyPlus, hKick],
    movesName: "強 コンドルスパイア",
    movesCondition:"",
    startup: 25,
    active: "25-37",
    recovery: 16,
    hit: "Down",
    block: -8,
    cancel: "×",
    tips:["11-39F 空中判定"],
    hitboxImage:"",
  }, {
    type:"必殺技",
    commands: [keyDown, keyDR, keyRight, keyPlus, anyKick,anyKick],
    movesName: "OD コンドルスパイア",
    movesCondition:"",
    startup: 15,
    active: "15-27",
    recovery: 16,
    hit: "Down",
    block: -8,
    cancel: "SA2",
    tips:["7-29F 空中判定","SA2 スカイサンダーバードでのみキャンセル可能"],
    hitboxImage:"",
  }, {
  type:"必殺技",
    commands: [keyDown, keyDR, keyRight, keyPlus, lKick],
  movesName: "[風纏い]弱 コンドルスパイア",
  movesCondition:"",
  startup: 9,
  active: "9-37",
  recovery: 14,
  hit: "Down",
  block: 1,
  cancel: "×",
  tips:["9-39F 空中判定"],
    hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyDown, keyDR, keyRight, keyPlus, mKick],
  movesName: "[風纏い]中 コンドルスパイア",
  movesCondition:"",
  startup: 13,
  active: "13-41",
  recovery: 14,
  hit: "Down",
  block: 1,
  cancel: "×",
  tips:["13-43F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyDown, keyDR, keyRight, keyPlus, hKick],
  movesName: "[風纏い]強 コンドルスパイア",
  movesCondition:"",
  startup: 17,
  active: "17-45",
  recovery: 14,
  hit: "Down",
  block: 1,
  cancel: "×",
  tips:["17-47F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyDown, keyDR, keyRight, keyPlus, anyKick,anyKick],
  movesName: "OD コンドルスパイア",
  movesCondition:"",
  startup: 9,
  active: "9-32",
  recovery: 14,
  hit: "Down",
  block: 2,
  cancel: "SA2",
  tips:["9-34F 空中判定","9-32F 飛び道具に対して無敵","SA2 スカイサンダーバードでのみキャンセル可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands: [keyRight, keyDown, keyDR, keyPlus, lPunch],
  movesName: "弱 トマホークバスター",
  movesCondition:"",
  startup: 6,
  active: "6-16",
  recovery: "20+着地後12",
  hit: "Down",
  block: -27,
  cancel: "×",
  tips: ["1-10F 空中判定の攻撃に対して無敵","7-37F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyRight, keyDown, keyDR, keyPlus, mPunch],
  movesName: "中 トマホークバスター",
  movesCondition:"",
  startup: 8,
  active: "8-19",
  recovery: "24+着地後12",
  hit: "Down",
  block: -32,
  cancel: "×",
  tips: ["1-12F 空中判定の攻撃に対して無敵","9-44F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyRight, keyDown, keyDR, keyPlus, hPunch],
  movesName: "強 トマホークバスター",
  movesCondition:"",
  startup: 10,
  active: "10-23",
  recovery: "25+着地後12",
  hit: "Down",
  block: -35,
  cancel: "×",
  tips:["1-14F 空中判定の攻撃に対して無敵","11-49F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyRight, keyDown, keyDR, keyPlus, hPunch],
  movesName: "OD トマホークバスター",
  movesCondition:"",
  startup: 6,
  active: "6-17",
  recovery: "27+着地後15",
  hit: "Down",
  block: -35,
  cancel: "SA2",
  tips:["1-10F 空中判定の攻撃に対して無敵","1-10F 投げに対して無敵","7-45F 空中判定","※OD コンドルダイブへのみ派生可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands: [keyRight, keyDown, keyDR, keyPlus, mPunch],
  movesName: "[風纏い]弱 トマホークバスター",
  movesCondition:"",
  startup: 4,
  active: "4-16",
  recovery: "20+着地後12",
  hit: "Down",
  block: -25,
  cancel: "SA3",
  tips: ["1-10F 空中判定の攻撃に対して無敵","7-37F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands: [keyRight, keyDown, keyDR, keyPlus, mPunch],
  movesName: "[風纏い]中 トマホークバスター",
  movesCondition:"",
  startup: 6,
  active: "6-19",
  recovery: "24+着地後12",
  hit: "Down",
  block: -30,
  cancel: "SA3",
  tips: ["1-12F 空中判定の攻撃に対して無敵","9-44F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyRight, keyDown, keyDR, keyPlus, hPunch],
  movesName: "[風纏い]強 トマホークバスター",
  movesCondition:"",
  startup: 8,
  active: "8-23",
  recovery: "25+着地後12",
  hit: "Down",
  block: -33,
  cancel: "×",
  tips: ["1-14F 空中判定の攻撃に対して無敵","11-49F 空中判定"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyRight, keyDown, keyDR, keyPlus, hPunch],
  movesName: "[風纏い]OD トマホークバスター",
  movesCondition:"",
  startup: 4,
  active: "4-17",
  recovery: "27+着地後15",
  hit: "Down",
  block: -35,
  cancel: "SA2",
  tips: ["1-10F 空中判定の攻撃に対して無敵","1-10F 投げに対して無敵","7-45F 空中判定","OD コンドルダイブへのみ派生可能"],
  hitboxImage:"",
},  {
  type:"必殺技",
  commands: [anyPunch,anyPunch],
  movesName: "コンドルダイブ",
  movesCondition:"(垂直or前ジャンプ中に)",
  startup: 12,
  active: "12-着地まで",
  recovery: "着地後24",
  hit: "Down",
  block: -24,
  cancel: "×",
  tips:["めくり性能"],
  hitboxImage:"",
},  {
  type:"必殺技",
  commands: [anyPunch,anyPunch,anyPunch],
  movesName: "OD コンドルダイブ",
  movesCondition:"(垂直or前じゃぷ中に) (ODトマホークバスター中に)",
  startup: 12,
  active: "12-着地まで",
  recovery: "着地後24",
  hit: "Down",
  block: "-24",
  cancel: "×",
  tips:["めくり性能","OD トマホークバスターからの派生版はコンボ補正35%"],
  hitboxImage:"",
},  {
  type:"必殺技",
  commands: [anyPunch,anyPunch],
  movesName: "[風纏い]コンドルダイブ",
  movesCondition:"(垂直or前ジャンプ中に)",
  startup: 12,
  active: "12-着地まで",
  recovery: "着地後24",
  hit: "Down",
  block: -23,
  cancel: "×",
  tips:["めくり性能","初段ヒット時、次のフレームで2段目が発生"],
  hitboxImage:"",
},  {
  type:"必殺技",
  commands: [anyPunch,anyPunch,anyPunch],
  movesName: "[風纏い]OD コンドルダイブ",
  movesCondition:"(垂直or前ジャンプ中に) (ODトマホークバスター中に)",
  startup: 12,
  active: "12-着地まで",
  recovery: "着地後24",
  hit: "Down",
  block: -23,
  cancel: "×",
  tips:["めくり性能","初段ヒット時、次のフレームで2段目が発生","OD トマホークバスターからの派生版はコンボ補正35%"],
  hitboxImage:"",
},  {
  type:"必殺技",
  commands: [keyCircle,keyPlus,lPunch],
  movesName: "弱 メキシカンタイフーン",
  movesCondition:"",
  startup: 5,
  active: "5-7",
  recovery: 53,
  hit: "Down",
  block: "",
  cancel: "",
  tips:["PC時ダメージ(2300)"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyCircle,keyPlus,mPunch],
  movesName: "中 メキシカンタイフーン",
  movesCondition:"",
  startup: 5,
  active: "5-7",
  recovery: 53,
  hit: "Down",
  block: "",
  cancel: "",
  tips:["PC時ダメージ（2760）"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyCircle,keyPlus,hPunch],
  movesName: "弱 メキシカンタイフーン",
  movesCondition:"",
  startup: 5,
  active: "5-7",
  recovery: 53,
  hit: "Down",
  block: "",
  cancel: "",
  tips:["PC時ダメージ（3220）"],
  hitboxImage:"",
}, {
  type:"必殺技",
  commands: [keyCircle,keyPlus,anyPunch,anyPunch],
  movesName: "OD メキシカンタイフーン",
  movesCondition:"",
  startup: 5,
  active: "5-7",
  recovery: 53,
  hit: "Down",
  block: "",
  cancel: "",
  tips:["PC時ダメージ（3350）"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands: [keyDown, keyDR, keyRight, keyDown, keyDR, keyRight, keyPlus, anyPunch],
  movesName: "SA1 ブリージングホーク",
  movesCondition:"",
  startup: 13,
  active: "13-50",
  recovery: 54,
  hit: "Down",
  block: -36,
  cancel: "×",
  tips:["1-14F 打撃・投げに対して無敵","2段目ヒット時に派生","最低保障ダメージ30%","C/PCで数値が変動しない"],
  hitboxImage:"",
}, {
  type:"スーパーアーツ",
  commands: [keyDown, keyDR, keyRight, keyDown, keyDR, keyRight, keyPlus,anyKick],
  movesName: "SA2 サンダーバード",
  movesCondition:"",
  startup: 9,
  active: "9-41",
  recovery: "39+着地後24",
  hit: "Down",
  block: -48,
  cancel: "×",
  tips: ["1-41F 完全無敵","7-80F 空中判定","最低保障ダメージ40%","C/PCで数値が変動しない"],
  hitboxImage:"",
}, {
  type:"スーパーアーツ",
  commands: [keyDown, keyDR, keyRight, keyDown, keyDR, keyRight, keyPlus,anyKick],
  movesName: "[風纏い]SA2 サンダーバード",
  movesCondition:"",
  startup: 9,
  active: "9-41",
  recovery: "39+着地後24",
  hit: "Down",
  block: -48,
  cancel: "×",
  tips: ["1-41F 完全無敵","7-80F 空中判定","最低保障ダメージ40%","C/PCで数値が変動しない"],
  hitboxImage:"",
},  {
  type:"スーパーアーツ",
  commands: [keyDown, keyDR, keyRight, keyDown, keyDR, keyRight, keyPlus,anyKick,],
  movesName: "SA2 スカイサンダーバード",
  movesCondition:"(ジャンプ中に)",
  startup: 9,
  active: "9-41",
  recovery: "着地後25",
  hit: "Down",
  block: -54,
  cancel: "×",
  tips:["1-41F 完全無敵","空中判定","最低保障ダメージ40%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands: [keyDown, keyDR, keyRight, keyDown, keyDR, keyRight, keyPlus,anyKick,],
  movesName: "[風纏い]]SA2 スカイサンダーバード",
  movesCondition:"(ジャンプ中に)",
  startup: 9,
  active: "9-41",
  recovery: "着地後25",
  hit: "Down",
  block: -54,
  cancel: "×",
  tips:["1-41F 完全無敵","空中判定","最低保障ダメージ40%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands: [keyDown, keyDL,keyLeft,keyDown,keyDL,keyLeft,keyPlus,anyPunch],
  movesName: "SA3 レイジングタイフーン",
  movesCondition:"",
  startup: 7,
  active: "7-8",
  recovery: 106,
  hit: "Down",
  block: "",
  cancel: "×",
  tips: ["1-8F完全無敵","最低保障ダメージ50%","C/PCで数値が変動しない","HP25%以下で性能変化"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands: [keyDown, keyDL,keyLeft,keyDown,keyDL,keyLeft,keyPlus,anyPunch],
  movesName: "CA レイジングタイフーン",
  movesCondition:"(HP25%以下で)",
  startup: 7,
  active: "7-8",
  recovery: 106,
  hit: "Down",
  block: "",
  cancel: "×",
  tips: ["1-8F完全無敵","最低保障ダメージ50%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"投げ",
  commands: [keyNutral, keyPlus, lPunch, lKick],
  movesName: "キャニオンスロー",
  movesCondition:"",
  startup: "5",
  active: "5-7",
  recovery: "23",
  hit: "Down",
  block: "",
  cancel: "×",
  tips:[""],
  hitboxImage:"",
}, {
  type:"投げ",
  commands: [keyLeft, keyPlus, lPunch, lKick],
  movesName: "クリフフォール",
  movesCondition:"",
  startup: "5",
  active: "5-7",
  recovery: "23",
  hit: "Down",
  block: "",
  cancel: "×",
  tips:[""],
  hitboxImage:"",
}]