import kenImage from './ken-top.png'
import p1Image from './ken-1p-image.png'
import p2Image from './ken-2p-image.png'
import anyPunch from '../CommandImages/p-any-icon.png'
import lPunch from '../CommandImages/p-l-icon.png'
import mPunch from '../CommandImages/p-m-icon.png'
import hPunch from '../CommandImages/p-h-icon.png'
import anyKick from '../CommandImages/k-any-icon.png'
import lKick from '../CommandImages/k-l-icon.png'
import mKick from '../CommandImages/k-m-icon.png'
import hKick from '../CommandImages/k-h-icon.png'
import keyPlus from '../CommandImages/plus-icon.png'
import keyDown from '../CommandImages/down-icon.png'
import keyRight from '../CommandImages/right-icon.png'
import keyLeft from '../CommandImages/left-icon.png'
import keyDR from '../CommandImages/down-right-icon.png'
import keyDL from '../CommandImages/down-left-icon.png'
import keyNutral from '../CommandImages/nutral-icon.png'
import keyNext from '../CommandImages/key-next.png'
import keyOr from '../CommandImages/or-icon.png'
import kenLPunch from './lPunch.gif'


export const kenDetails:{
  name:string;
  strongpoints:string[];
  weakpoints:string[];
  topImage:string;
  p1Image:string;
  p2Image:string;
} = {
  name:"KEN",
  strongpoints:["・弾と昇竜のスタンダードな強さ","・画面端への運び性能","・位置入れ替えもできるコンボ選択肢"],
  weakpoints:["・目立った弱点はそこまでない","・少し高いコンボ難易度","・人口の多さから対策されやすい"],
  topImage:kenImage,
  p1Image:p1Image,
  p2Image:p2Image,
}

export const kenMoves:{
  [key:string]: string|string[]|number|number[],
  type:string
  commands:string[]
  movesName:string
  movesCondition:string
  startup:any
  active:any
  recovery:any
  hit:any
  block:any
  cancel:any
  tips:string[]
  hitboxImage:string 
}[]= [{
  type:"通常技",
  commands:[lPunch],
  movesName:"立ち弱P(ジャブ)",
  movesCondition:"",
  startup:4,
  active:"4-6",
  recovery:7,
  hit:4,
  block:-1,
  cancel:"〇",
  tips:["連打キャンセル対応"],
  hitboxImage:kenLPunch,
},{
  type:"通常技",
  commands:[lKick],
  movesName:"立ち弱K(ローキック)",
  movesCondition:"",
  startup:5,
  active:"5-6",
  recovery:12,
  hit:0,
  block:-2,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[mPunch],
  movesName:"立ち中P(顎撥)",
  movesCondition:"",
  startup:5,
  active:"5-8",
  recovery:14,
  hit:4,
  block:-2,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[mKick],
  movesName:"立ち中K(上段横蹴り)",
  movesCondition:"",
  startup:8,
  active:"8-10",
  recovery:20,
  hit:3,
  block:-5,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[hPunch],
  movesName:"立ち強P(正拳突き)",
  movesCondition:"",
  startup:10,
  active:"10-14",
  recovery:17,
  hit:3,
  block:-2,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[hKick],
  movesName:"立ち強K(一文字蹴り)",
  movesCondition:"",
  startup:12,
  active:"12-13",
  recovery:23,
  hit:1,
  block:-5,
  cancel:"×",
  tips:["空振り、アーマーヒット時硬直2F増加","PC時きりもみダウン"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,lPunch],
  movesName:"しゃがみ弱P(ジャブ)",
  movesCondition:"",
  startup:4,
  active:"4-5",
  recovery:9,
  hit:5,
  block:-1,
  cancel:"〇",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,lKick],
  movesName:"しゃがみ弱K(キック)",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:10,
  hit:1,
  block:-3,
  cancel:"×",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,mPunch],
  movesName:"しゃがみ中P(ストレート)",
  movesCondition:"",
  startup:5,
  active:"5-8",
  recovery:14,
  hit:4,
  block:-2,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,mKick],
  movesName:"しゃがみ中K(くるぶしキック)",
  movesCondition:"",
  startup:7,
  active:"7-9",
  recovery:20,
  hit:3,
  block:-5,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,hPunch],
  movesName:"しゃがみ強P(突き上げアッパー)",
  movesCondition:"",
  startup:8,
  active:"8-11",
  recovery:24,
  hit:3,
  block:-10,
  cancel:"〇",
  tips:["キャンセルは持続の2F目まで"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,hKick],
  movesName:"しゃがみ強K(回転足払い)",
  movesCondition:"",
  startup:8,
  active:"8-10",
  recovery:24,
  hit:"Down",
  block:-10,
  cancel:"×",
  tips:["ハードノックダウン","C/PC時ダウン時間延長","ガード時硬直1F増加"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[anyKick,anyKick],
  movesName:"奮迅脚",
  movesCondition:"",
  startup:"",
  active:"",
  recovery:"全体45",
  hit:"",
  block:"",
  cancel:"×",
  tips:["12Fから各派生技に移行可"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[lKick],
  movesName:"急停止",
  movesCondition:"(奮迅脚中に)",
  startup:"",
  active:"",
  recovery:"全体16",
  hit:"",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[mKick],
  movesName:"紫電カカト落とし",
  movesCondition:"(奮迅脚中に)",
  startup:18,
  active:"18-20",
  recovery:20,
  hit:3,
  block:-3,
  cancel:"SA3",
  tips:["SA3キャンセル対応"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[hKick],
  movesName:"踏み込み前蹴り",
  movesCondition:"(奮迅脚中に)",
  startup:10,
  active:"10-13",
  recovery:20,
  hit:3,
  block:-3,
  cancel:"SA",
  tips:["SAキャンセル対応"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[mPunch,keyNext,hPunch],
  movesName:"顎撥二連",
  movesCondition:"",
  startup:11,
  active:"11-13",
  recovery:27,
  hit:"Down",
  block:-14,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[mKick,keyNext,mKick],
  movesName:"閃光連脚(2段目)",
  movesCondition:"",
  startup:11,
  active:"11-12",
  recovery:27,
  hit:"Down",
  block:-12,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyNext,hKick],
  movesName:"閃光連脚(3段目)",
  movesCondition:"(閃光連脚2段目後に)",
  startup:13,
  active:"13-15",
  recovery:28,
  hit:"Down",
  block:-11,
  cancel:"×",
  tips:["動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,lPunch],
  movesName:"弱 波動拳",
  movesCondition:"",
  startup:16,
  active:"",
  recovery:"全体49",
  hit:-1,
  block:-7,
  cancel:"SA3",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,mPunch],
  movesName:"中 波動拳",
  movesCondition:"",
  startup:14,
  active:"",
  recovery:"全体49",
  hit:-3,
  block:-9,
  cancel:"SA3",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,hPunch],
  movesName:"強 波動拳",
  movesCondition:"",
  startup:12,
  active:"",
  recovery:"全体49",
  hit:-5,
  block:-11,
  cancel:"SA3",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,anyPunch,anyPunch],
  movesName:"OD 波動拳",
  movesCondition:"",
  startup:12,
  active:"",
  recovery:"全体40",
  hit:-2,
  block:2,
  cancel:"SA2",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,lPunch],
  movesName:"弱 昇龍拳",
  movesCondition:"",
  startup:5,
  active:"5-14",
  recovery:"21+着地後12",
  hit:"Down",
  block:-23,
  cancel:"SA3",
  tips:["1-14F 空中判定の攻撃に対して無敵","8-35空中判定","持続の3F目以降は個別ダメージ(800)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,mPunch],
  movesName:"中 昇龍拳",
  movesCondition:"",
  startup:6,
  active:"6-15",
  recovery:"28+着地後12",
  hit:"Down",
  block:-28,
  cancel:"SA3",
  tips:["1-8F 空中判定の攻撃に対して無敵","9-43空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,hPunch],
  movesName:"強 昇龍拳",
  movesCondition:"",
  startup:7,
  active:"7-16",
  recovery:"35+着地後15",
  hit:"Down",
  block:-36,
  cancel:"SA3",
  tips:["1-9F 空中判定の攻撃に対して無敵","5-11F 飛び道具無敵","11-51空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,anyPunch,anyPunch],
  movesName:"OD 昇龍拳",
  movesCondition:"",
  startup:6,
  active:"6-19",
  recovery:"35+着地後15",
  hit:"Down",
  block:-40,
  cancel:"×",
  tips:["1-10F 完全無敵","9-24,33-74F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,anyPunch],
  movesName:"[奮迅脚] 昇龍拳",
  movesCondition:"(奮迅脚中に)",
  startup:9,
  active:"9-18",
  recovery:"33+着地後15",
  hit:"Down",
  block:-35,
  cancel:"SA3",
  tips:["1-12F 空中判定の攻撃に対して無敵","3-12F 飛び道具無敵","9-52空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,lKick],
  movesName:"弱 竜巻旋風脚",
  movesCondition:"",
  startup:4,
  active:"4-14",
  recovery:32,
  hit:"Down",
  block:-14,
  cancel:"×",
  tips:["5-28F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,mKick],
  movesName:"中 竜巻旋風脚",
  movesCondition:"",
  startup:14,
  active:"14-30",
  recovery:31,
  hit:"Down",
  block:-12,
  cancel:"×",
  tips:["8-41F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,hKick],
  movesName:"強 竜巻旋風脚",
  movesCondition:"",
  startup:16,
  active:"16-47",
  recovery:31,
  hit:"Down",
  block:-12,
  cancel:"×",
  tips:["10-61F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyKick,anyKick],
  movesName:"OD 竜巻旋風脚",
  movesCondition:"",
  startup:9,
  active:"9-56",
  recovery:"22+着地後12",
  hit:"Down",
  block:-61,
  cancel:"×",
  tips:["10-77F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyKick],
  movesName:"[奮迅脚] 竜巻旋風脚",
  movesCondition:"(奮迅脚中に)",
  startup:13,
  active:"13-58",
  recovery:20,
  hit:3,
  block:-9,
  cancel:"×",
  tips:["2,4,6,8,10段目は正面の相手に当たらない","10-61F空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyKick],
  movesName:"空中竜巻旋風脚",
  movesCondition:"(前ジャンプ中に)",
  startup:11,
  active:"11-27",
  recovery:"着地後14",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyKick,anyKick],
  movesName:"OD 空中竜巻旋風脚",
  movesCondition:"(前ジャンプ中に)",
  startup:11,
  active:"11-28",
  recovery:"着地後14",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["1-77F 空中判定","2,4段目は正面の相手に当たらない","(2,4段目の攻撃はダメージ700,SAゲージ増加量600)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,lKick],
  movesName:"弱 龍尾脚",
  movesCondition:"",
  startup:18,
  active:"18-23",
  recovery:21,
  hit:2,
  block:-4,
  cancel:"×",
  tips:["18-20F 地上の相手に当たらない","21-23F ダメージ950","9-28F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,mKick],
  movesName:"中 龍尾脚",
  movesCondition:"",
  startup:16,
  active:"16-18",
  recovery:24,
  hit:2,
  block:-7,
  cancel:"×",
  tips:["23-24F 地上の相手に当たらない","14-32F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,hKick],
  movesName:"強 龍尾脚",
  movesCondition:"",
  startup:28,
  active:"28-32",
  recovery:21,
  hit:3,
  block:1,
  cancel:"×",
  tips:["28-29F 地上の相手に当たらない","19-37F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,anyKick,anyKick],
  movesName:"OD 龍尾脚",
  movesCondition:"",
  startup:9,
  active:"9-24",
  recovery:24,
  hit:1,
  block:-9,
  cancel:"×",
  tips:["9-12F,18F 地上の相手に当たらない","10-27F 空中判定","2段目のみヒット時、追加のコンボ補正はかからない"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDown,keyDR,keyPlus,anyKick],
  movesName:"[奮迅脚] 龍尾脚",
  movesCondition:"(奮迅脚中に)",
  startup:9,
  active:"9-23",
  recovery:24,
  hit:2,
  block:-8,
  cancel:"×",
  tips:["9-12F,18-19F 地上の相手に当たらない","10-28F 空中判定","2段目のみヒット時、追加のコンボ補正はかからない"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,lKick],
  movesName:"弱 迅雷脚",
  movesCondition:"",
  startup:12,
  active:"12-14",
  recovery:28,
  hit:2,
  block:-8,
  cancel:"SA3",
  tips:["32-35F 風鎌蹴り、轟雷落としに派生可","30-35F 閃火脚に派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,mKick],
  movesName:"中 迅雷脚",
  movesCondition:"",
  startup:16,
  active:"16-18",
  recovery:24,
  hit:2,
  block:-7,
  cancel:"SA3",
  tips:["32-35F 風鎌蹴り、轟雷落としに派生可","30-35F 閃火脚に派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,hKick],
  movesName:"強 迅雷脚",
  movesCondition:"",
  startup:25,
  active:"25-27",
  recovery:19,
  hit:"Down",
  block:-2,
  cancel:"SA3",
  tips:["36-41F 風鎌蹴り、轟雷落としに派生可","34-41F 閃火脚に派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,anyKick,anyKick],
  movesName:"OD 迅雷脚",
  movesCondition:"",
  startup:13,
  active:"13-15",
  recovery:25,
  hit:-4,
  block:-7,
  cancel:"SA2",
  tips:["21-27F OD風鎌蹴り、OD轟雷落としに派生可","19-27F OD閃火脚に派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,lKick],
  movesName:"風鎌蹴り",
  movesCondition:"(迅雷脚中に)",
  startup:6,
  active:"6-9",
  recovery:19,
  hit:3,
  block:-5,
  cancel:"SA3",
  tips:["動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,lKick],
  movesName:"OD 風鎌蹴り",
  movesCondition:"(OD迅雷脚中に)",
  startup:6,
  active:"6-8",
  recovery:20,
  hit:3,
  block:-5,
  cancel:"SA2",
  tips:["11F 火砕蹴に派生可","動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,lKick],
  movesName:"火砕蹴",
  movesCondition:"(OD風鎌蹴り後に)",
  startup:15,
  active:"15-17",
  recovery:29,
  hit:"Down",
  block:-12,
  cancel:"SA2",
  tips:["動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,mKick],
  movesName:"轟雷落とし",
  movesCondition:"(迅雷脚中に)",
  startup:18,
  active:"18-20",
  recovery:29,
  hit:3,
  block:-3,
  cancel:"SA3",
  tips:["動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,mKick],
  movesName:"OD 轟雷落とし",
  movesCondition:"(OD迅雷脚中に)",
  startup:17,
  active:"17-19",
  recovery:24,
  hit:-3,
  block:-7,
  cancel:"SA2",
  tips:["24F 火砕蹴に派生可","動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,anyKick],
  movesName:"火砕蹴",
  movesCondition:"(OD轟雷落とし後に)",
  startup:11,
  active:"11-13",
  recovery:29,
  hit:"Down",
  block:-12,
  cancel:"SA2",
  tips:["動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,hKick],
  movesName:"閃火脚",
  movesCondition:"(迅雷脚中に)",
  startup:10,
  active:"10-12",
  recovery:25,
  hit:"Down",
  block:-3,
  cancel:"SA3",
  tips:["動作中常に被PC判定","しゃがみ状態の敵に当たらない"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,hKick],
  movesName:"OD 閃火脚",
  movesCondition:"(OD迅雷脚中に)",
  startup:10,
  active:"10-13",
  recovery:20,
  hit:"Down",
  block:-4,
  cancel:"SA2",
  tips:["22F 火砕蹴に派生可","動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyPlus,anyKick],
  movesName:"火砕蹴",
  movesCondition:"(OD閃火脚後に)",
  startup:15,
  active:"15-17",
  recovery:37,
  hit:"Down",
  block:-20,
  cancel:"SA2",
  tips:["動作中常に被PC判定"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDL,keyLeft,keyDown,keyDL,keyLeft,keyPlus,anyKick],
  movesName:"SA1 龍尾烈脚",
  movesCondition:"",
  startup:"7",
  active:"7-9",
  recovery:"41",
  hit:"Down",
  block:-24,
  cancel:"×",
  tips:["1F 完全無敵","2-9F 打撃･投げに対して無敵","最低保証ダメージ30%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyKick],
  movesName:"SA2 疾風迅雷脚",
  movesCondition:"",
  startup:6,
  active:"6-60",
  recovery:"32",
  hit:"Down",
  block:-19,
  cancel:"×",
  tips:["1F 完全無敵","ヒット時6段目以降に派生","最低保証ダメージ40%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyPunch],
  movesName:"SA3 神龍烈破",
  movesCondition:"",
  startup:7,
  active:"7-45",
  recovery:45,
  hit:"Down",
  block:"-30",
  cancel:"×",
  tips:["1-18F 完全無敵","最低保証ダメージ50%","C/PCで数値が変動しない","HP25%以下で性能変化"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyPunch],
  movesName:"CA 神龍烈破",
  movesCondition:"(HP25%以下で)",
  startup:7,
  active:"7-45",
  recovery:45,
  hit:"Down",
  block:"-30",
  cancel:"×",
  tips:["1-18F 完全無敵","最低保証ダメージ50%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"投げ",
  commands:[keyNutral,keyOr,keyRight,keyPlus,lPunch,lKick],
  movesName:"掴み膝蹴り",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:23,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"投げ",
  commands:[keyLeft,keyPlus,lPunch,lKick],
  movesName:"地獄車",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:23,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
}]