import blankaImage from './blanka-top.png'
import p1Image from './blanka-1p-image.png'
import p2Image from './blanka-2p-image.png'
import anyPunch from '../CommandImages/p-any-icon.png'
import lPunch from '../CommandImages/p-l-icon.png'
import mPunch from '../CommandImages/p-m-icon.png'
import hPunch from '../CommandImages/p-h-icon.png'
import anyKick from '../CommandImages/k-any-icon.png'
import lKick from '../CommandImages/k-l-icon.png'
import mKick from '../CommandImages/k-m-icon.png'
import hKick from '../CommandImages/k-h-icon.png'
import keyPlus from '../CommandImages/plus-icon.png'
import keyUp from '../CommandImages/up-icon.png'
import keyDown from '../CommandImages/down-icon.png'
import keyRight from '../CommandImages/right-icon.png'
import keyLeft from '../CommandImages/left-icon.png'
import keyDR from '../CommandImages/down-right-icon.png'
import keyDL from '../CommandImages/down-left-icon.png'
import keyHoldL from '../CommandImages/hold-left-icon.png'
import keyHoldD from '../CommandImages/hold-down-icon.png'
import keyNutral from '../CommandImages/nutral-icon.png'
import keyOr from '../CommandImages/or-icon.png'


export const blankaDetails = [{
  name:"BLANKA",
  strongpoints:["aaaaa","bbbbb","ccccc"],
  weakpoints:["ddddd","eeeee","fffff"],
  topImage:blankaImage,
  p1Image:p1Image,
  p2Image:p2Image,
}]

export const blankaMoves = [{
  type:"通常技",
  commands:[lPunch],
  movesName:"立ち弱P(ベアアタック)",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:10,
  hit:3,
  block:-3,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[lKick],
  movesName:"立ち弱K(ビーストキック)",
  movesCondition:"",
  startup:4,
  active:"4-7",
  recovery:7,
  hit:5,
  block:-2,
  cancel:"〇",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[mPunch],
  movesName:"立ち中P(ビーストチョップ)",
  movesCondition:"",
  startup:10,
  active:"10-12",
  recovery:15,
  hit:3,
  block:-4,
  cancel:"SA",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[mKick],
  movesName:"立ち中K(ブラッディ―テイル)",
  movesCondition:"",
  startup:8,
  active:"8-10",
  recovery:17,
  hit:4,
  block:-2,
  cancel:"〇",
  tips:["空振り時硬直3F増加"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[hPunch],
  movesName:"立ち強P(ジャングルアーチ)",
  movesCondition:"",
  startup:10,
  active:"10-16",
  recovery:22,
  hit:3,
  block:-3,
  cancel:"〇",
  tips:["強制立ち効果"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[hKick],
  movesName:"立ち強K(ワイルドダンス)",
  movesCondition:"",
  startup:7,
  active:"7-15",
  recovery:18,
  hit:6,
  block:-4,
  cancel:"×",
  tips:["空中カウンター、空中PC時吹き飛びダウン","強制立ち効果"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,lPunch],
  movesName:"しゃがみ弱P(キャットクロー)",
  movesCondition:"",
  startup:6,
  active:"6-8",
  recovery:8,
  hit:4,
  block:-2,
  cancel:"〇",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,lKick],
  movesName:"しゃがみ弱K(ジャングルトラップ)",
  movesCondition:"",
  startup:5,
  active:"5-6",
  recovery:10,
  hit:3,
  block:-3,
  cancel:"×",
  tips:["連打キャンセル対応"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,mPunch],
  movesName:"しゃがみ中P(ベアクロー)",
  movesCondition:"",
  startup:9,
  active:"9-13",
  recovery:16,
  hit:-1,
  block:-5,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,mKick],
  movesName:"しゃがみ中K(ビーストステップ)",
  movesCondition:"",
  startup:8,
  active:"8-10",
  recovery:16,
  hit:5,
  block:-5,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,hPunch],
  movesName:"しゃがみ強P(スネークアッパー)",
  movesCondition:"",
  startup:15,
  active:"15-19",
  recovery:20,
  hit:0,
  block:-5,
  cancel:"×",
  tips:["PC時吹き飛びダウン","強制立ち効果"],
  hitboxImage:"",
},{
  type:"通常技",
  commands:[keyDown,keyPlus,hKick],
  movesName:"しゃがみ強K(ビーストテイル)",
  movesCondition:"",
  startup:11,
  active:"11-14",
  recovery:23,
  hit:"Down",
  block:-12,
  cancel:"×",
  tips:["C/PC時ダウン時間延長"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyRight,keyPlus,mPunch],
  movesName:"ロッククラッシュ",
  movesCondition:"",
  startup:20,
  active:"20-22",
  recovery:20,
  hit:3,
  block:-2,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyRight,keyPlus,mKick],
  movesName:"ダブルニーボンバー",
  movesCondition:"",
  startup:9,
  active:"9-20",
  recovery:18,
  hit:6,
  block:-2,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyLeft,keyPlus,mKick],
  movesName:"ワイルドエッジ",
  movesCondition:"",
  startup:9,
  active:"9-14",
  recovery:12,
  hit:8,
  block:2,
  cancel:"〇",
  tips:[""],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyRight,keyPlus,hPunch],
  movesName:"ワイルドネイル",
  movesCondition:"",
  startup:18,
  active:"18-21",
  recovery:31,
  hit:"Down",
  block:-15,
  cancel:"△",
  tips:["33-34F フィアーダウンへ派生可","地上PC時膝崩れ","空中PC時床バウンド"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyDR,keyPlus,hPunch],
  movesName:"アマゾンリバーラン",
  movesCondition:"",
  startup:14,
  active:"14-23",
  recovery:22,
  hit:"Down",
  block:-18,
  cancel:"×",
  tips:["C/PC時ハードノックダウン"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyDown,keyPlus,anyPunch,anyPunch],
  movesName:"フィアーダウン",
  movesCondition:"",
  startup:"",
  active:"",
  recovery:"全体98",
  hit:"",
  block:"",
  cancel:"×",
  tips:["動作中に下方向入力を続けた場合伏せ部分の動作を48F延長可","伏せ動作中に上方向入力で動作を中断可","18F-111F(最延長時) 専用技及びサプライズフォワード、サプライズバックへ派生可"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[anyPunch],
  movesName:"ワイルドリフト",
  movesCondition:"(フィアーダウン中に)",
  startup:8,
  active:"8-14",
  recovery:31,
  hit:"Down",
  block:-21,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[anyKick],
  movesName:"レイドジャンプ",
  movesCondition:"",
  startup:"",
  active:"",
  recovery:"43+着地後12",
  hit:"",
  block:"",
  cancel:"×",
  tips:["9-43F 空中判定","15-43F 空中での通常技及び必殺技へ派生可"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyRight,keyPlus,anyKick,anyKick,anyKick],
  movesName:"サプライズフォワード",
  movesCondition:"",
  startup:"",
  active:"",
  recovery:"全体27",
  hit:"",
  block:"",
  cancel:"×",
  tips:["必殺技キャンセル可能な通常技及び特殊技からキャンセル可能"],
  hitboxImage:"",
},{
  type:"特殊技",
  commands:[keyLeft,keyPlus,anyKick,anyKick,anyKick],
  movesName:"サプライズバック",
  movesCondition:"",
  startup:"",
  active:"",
  recovery:"全体32",
  hit:"",
  block:"",
  cancel:"×",
  tips:["11-21F 空中判定","必殺技キャンセル可能な通常技及び特殊技からキャンセル可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyPunch],
  movesName:"エレクトリックサンダー",
  movesCondition:"",
  startup:10,
  active:"10-21",
  recovery:17,
  hit:"Down",
  block:-3,
  cancel:"SA3",
  tips:["発動後にボタンホールドで延長可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyPunch],
  movesName:"[ライトニングビースト]エレクトリックサンダー",
  movesCondition:"",
  startup:10,
  active:"10-21",
  recovery:17,
  hit:"Down",
  block:-3,
  cancel:"SA3",
  tips:["発動後にボタンホールドで延長可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyPunch,anyPunch],
  movesName:"OD エレクトリックサンダー",
  movesCondition:"",
  startup:10,
  active:"10-18",
  recovery:17,
  hit:"Down",
  block:4,
  cancel:"SA2",
  tips:["発動後にボタンホールドで延長可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDL,keyLeft,keyPlus,anyPunch,anyPunch],
  movesName:"[ライトニングビースト]OD エレクトリックサンダー",
  movesCondition:"",
  startup:10,
  active:"10-18",
  recovery:17,
  hit:"Down",
  block:4,
  cancel:"SA2",
  tips:["発動後にボタンホールドで延長可能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,lPunch],
  movesName:"弱 ローリングアタック",
  movesCondition:"",
  startup:10,
  active:"10-20",
  recovery:11,
  hit:"Down",
  block:-23,
  cancel:"SA3",
  tips:["10-23F 空中判定"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,lPunch],
  movesName:"[ライトニングビースト]弱 ローリングアタック",
  movesCondition:"",
  startup:10,
  active:"10-20",
  recovery:11,
  hit:"Down",
  block:-21,
  cancel:"SA3",
  tips:["10-23F 空中判定","SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,mPunch],
  movesName:"中 ローリングアタック",
  movesCondition:"",
  startup:12,
  active:"12-30",
  recovery:11,
  hit:"Down",
  block:-23,
  cancel:"SA3",
  tips:["12-32F 空中判定","PC時吹き飛び時間延長","持続の11F目までSA3でキャンセル可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,mPunch],
  movesName:"[ライトニングビースト]中 ローリングアタック",
  movesCondition:"",
  startup:12,
  active:"12-30",
  recovery:11,
  hit:"Down",
  block:-21,
  cancel:"SA3",
  tips:["12-32F 空中判定","SA2タイマー100消費","PC時吹き飛び時間延長","ヒット、ガード時ローリングキャノンへ派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,hPunch],
  movesName:"強 ローリングアタック",
  movesCondition:"",
  startup:22,
  active:"22-41",
  recovery:26,
  hit:"Down",
  block:-15,
  cancel:"SA3",
  tips:["20-42F 空中判定","PC時吹き飛び時間延長","持続の6F目までSA3でキャンセル可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,hPunch],
  movesName:"[ライトニングビースト]強 ローリングアタック",
  movesCondition:"",
  startup:22,
  active:"22-41",
  recovery:26,
  hit:"Down",
  block:-21,
  cancel:"SA3",
  tips:["20-42F 空中判定","SA2タイマー100消費","PC時吹き飛び時間延長","ヒット、ガード時ローリングキャノンへ派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,anyPunch,anyPunch],
  movesName:"OD ローリングアタック",
  movesCondition:"",
  startup:18,
  active:"18-39",
  recovery:17,
  hit:"Down",
  block:-7,
  cancel:"SA2",
  tips:["18-40F 空中判定","持続の2F目までSA2、SA3でキャンセル可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,anyPunch,anyPunch],
  movesName:"[ライトニングビースト]OD ローリングアタック",
  movesCondition:"",
  startup:18,
  active:"18-39",
  recovery:17,
  hit:"Down",
  block:-7,
  cancel:"×",
  tips:["18-40F 空中判定","SA2タイマー100消費","ガード時ローリングキャノンへ派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldD,keyUp,keyPlus,lKick],
  movesName:"弱 バーチカルローリング",
  movesCondition:"",
  startup:8,
  active:"8-27",
  recovery:"31+着地後17",
  hit:"Down",
  block:-27,
  cancel:"×",
  tips:["6-57F 空中判定","8-26F 空中判定の攻撃に対して無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldD,keyUp,keyPlus,lKick],
  movesName:"[ライトニングビースト]弱 バーチカルローリング",
  movesCondition:"",
  startup:8,
  active:"8-27",
  recovery:"31+着地後17",
  hit:"Down",
  block:-27,
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可","6-57F 空中判定","8-26F 空中判定の攻撃に対して無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldD,keyUp,keyPlus,mKick],
  movesName:"中 バーチカルローリング",
  movesCondition:"",
  startup:8,
  active:"8-27",
  recovery:"31+着地後17",
  hit:"Down",
  block:-27,
  cancel:"×",
  tips:["6-57F 空中判定","8-26F 空中判定の攻撃に対して無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldD,keyUp,keyPlus,mKick],
  movesName:"[ライトニングビースト]中 バーチカルローリング",
  movesCondition:"",
  startup:8,
  active:"8-27",
  recovery:"31+着地後17",
  hit:"Down",
  block:-27,
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可","6-57F 空中判定","8-26F 空中判定の攻撃に対して無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldD,keyUp,keyPlus,hKick],
  movesName:"強バーチカルローリング",
  movesCondition:"",
  startup:8,
  active:"8-27",
  recovery:"31+着地後17",
  hit:"Down",
  block:-27,
  cancel:"×",
  tips:["6-57F 空中判定","8-26F 空中判定の攻撃に対して無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldD,keyUp,keyPlus,hKick],
  movesName:"[ライトニングビースト]強 バーチカルローリング",
  movesCondition:"",
  startup:8,
  active:"8-27",
  recovery:"31+着地後17",
  hit:"Down",
  block:-27,
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可","6-57F 空中判定","8-26F 空中判定の攻撃に対して無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldD,keyUp,keyPlus,anyKick,anyKick],
  movesName:"OD バーチカルローリング",
  movesCondition:"",
  startup:7,
  active:"7-22",
  recovery:"31+着地後17",
  hit:"Down",
  block:-40,
  cancel:"×",
  tips:["4-53F 空中判定","1-10F 完全無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldD,keyUp,keyPlus,anyKick,anyKick],
  movesName:"[ライトニングビースト]OD バーチカルローリング",
  movesCondition:"",
  startup:7,
  active:"7-22",
  recovery:"31+着地後17",
  hit:"Down",
  block:-40,
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット時ローリングキャノンへ派生可","4-53F 空中判定","1-10F 完全無敵"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,lKick],
  movesName:"弱 バックステップローリング",
  movesCondition:"",
  startup:41,
  active:"41-着地まで",
  recovery:"着地後5",
  hit:9,
  block:3,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,lKick],
  movesName:"[ライトニングビースト]弱 バックステップローリング",
  movesCondition:"",
  startup:41,
  active:"41-着地まで",
  recovery:"着地後5",
  hit:9,
  block:3,
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,mKick],
  movesName:"中 バックステップローリング",
  movesCondition:"",
  startup:41,
  active:"41-着地まで",
  recovery:"着地後5",
  hit:8,
  block:2,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,mKick],
  movesName:"[ライトニングビースト]中 バックステップローリング",
  movesCondition:"",
  startup:41,
  active:"41-着地まで",
  recovery:"着地後5",
  hit:8,
  block:2,
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,hKick],
  movesName:"強 バックステップローリング",
  movesCondition:"",
  startup:41,
  active:"41-着地まで",
  recovery:"着地後5",
  hit:8,
  block:4,
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,hKick],
  movesName:"[ライトニングビースト]強 バックステップローリング",
  movesCondition:"",
  startup:41,
  active:"41-着地まで",
  recovery:"着地後5",
  hit:8,
  block:4,
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,anyKick,anyKick],
  movesName:"OD バックステップローリング",
  movesCondition:"",
  startup:8,
  active:"8-66",
  recovery:"着地後4",
  hit:10,
  block:6,
  cancel:"SA2",
  tips:["初段ヒット時吹き飛びダウン","初段の持続3F目までSA2、SA3でキャンセル可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyRight,keyDR,keyDown,keyDL,keyLeft,keyPlus,anyKick,anyKick],
  movesName:"[ライトニングビースト]OD バックステップローリング",
  movesCondition:"",
  startup:8,
  active:"8-66",
  recovery:"着地後4",
  hit:10,
  block:6,
  cancel:"SA2",
  tips:["初段ヒット時吹き飛びダウン","SA2タイマー100消費","回転部分のヒット、ガード時ローリングキャノンへ派生可"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,lPunch],
  movesName:"弱 エリアルローリング",
  movesCondition:"",
  startup:13,
  active:"13-着地まで",
  recovery:"着地後17",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["めくり性能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,lPunch],
  movesName:"[ライトニングビースト]弱 エリアルローリング",
  movesCondition:"",
  startup:13,
  active:"13-着地まで",
  recovery:"着地後17",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可","めくり性能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,mPunch],
  movesName:"中 エリアルローリング",
  movesCondition:"",
  startup:13,
  active:"13-着地まで",
  recovery:"着地後17",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["めくり性能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,mPunch],
  movesName:"[ライトニングビースト]中 エリアルローリング",
  movesCondition:"",
  startup:13,
  active:"13-着地まで",
  recovery:"着地後17",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可","めくり性能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,hPunch],
  movesName:"強 エリアルローリング",
  movesCondition:"",
  startup:13,
  active:"13-着地まで",
  recovery:"着地後17",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["めくり性能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,hPunch],
  movesName:"[ライトニングビースト]強 エリアルローリング",
  movesCondition:"",
  startup:13,
  active:"13-着地まで",
  recovery:"着地後17",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可","めくり性能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,anyPunch,anyPunch],
  movesName:"OD エリアルローリング",
  movesCondition:"",
  startup:13,
  active:"13-着地まで",
  recovery:"着地後10",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["めくり性能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyHoldL,keyRight,keyPlus,anyPunch,anyPunch],
  movesName:"[ライトニングビースト]OD エリアルローリング",
  movesCondition:"",
  startup:13,
  active:"13-着地まで",
  recovery:"着地後10",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["SA2タイマー100消費","ヒット、ガード時ローリングキャノンへ派生可","めくり性能"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,lKick],
  movesName:"弱 ワイルドハント",
  movesCondition:"",
  startup:34,
  active:"34-36",
  recovery:57,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["9-26F 空中判定","PC時個別ダメージ(1840)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,mKick],
  movesName:"中 ワイルドハント",
  movesCondition:"",
  startup:39,
  active:"39-41",
  recovery:57,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["14-36F 空中判定","PC時個別ダメージ(1955)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,hKick],
  movesName:"強 ワイルドハント",
  movesCondition:"",
  startup:43,
  active:"43-45",
  recovery:57,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["18-36F 空中判定","PC時個別ダメージ(2070)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDR,keyRight,keyPlus,anyKick,anyKick],
  movesName:"OD ワイルドハント",
  movesCondition:"",
  startup:32,
  active:"32-34",
  recovery:57,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["9-28F 空中判定","PC時個別ダメージ(2300)"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyDown,keyDown,keyPlus,anyPunch],
  movesName:"ブランカちゃん爆弾",
  movesCondition:"",
  startup:"",
  active:"",
  recovery:"全体50",
  hit:"",
  block:"",
  cancel:"×",
  tips:["人形の接地後1000F経過で消滅","1000F間に電撃を発する必殺技、SAを接触させると人形が飛び道具攻撃として起動する","投擲した人形がステージ端に接触時、跳ね返りによる軌道変化"],
  hitboxImage:"",
},{
  type:"必殺技",
  commands:[keyPlus,anyPunch],
  movesName:"ローリングキャノン",
  movesCondition:"(ライトニングビースト中のローリング系必殺技中に任意の方向）",
  startup:3,
  active:"3-27",
  recovery:"着地後9",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:["ローリング系必殺技から最大3回連続で派生可能","めくり性能"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyPunch],
  movesName:"SA1 シャウトオブアース",
  movesCondition:"",
  startup:8,
  active:"8-16",
  recovery:"全体78",
  hit:"Down",
  block:-29,
  cancel:"×",
  tips:["1F 完全無敵","2-10F 打撃・投げに対して無敵","最低保障ダメージ30%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyPunch],
  movesName:"[ライトニングビースト]SA1 シャウトオブアース",
  movesCondition:"",
  startup:8,
  active:"8-16",
  recovery:"全体78",
  hit:"Down",
  block:-29,
  cancel:"×",
  tips:["1F 完全無敵","2-10F 打撃・投げに対して無敵","最低保障ダメージ30%","C/PCで数値が変動しない"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDL,keyLeft,keyDown,keyDL,keyLeft,keyPlus,anyPunch],
  movesName:"SA2 ライトニングビースト",
  movesCondition:"",
  startup:"",
  active:"",
  recovery:"全体10",
  hit:"",
  block:"",
  cancel:"×",
  tips:["SA2タイマー1500","発動中、ワイルドハント以外の必殺技が性質変化","発動中、ローリング系必殺技から「ローリングキャノン」が派生可能になる","発動中[ローリングアタック],[バーチカルローリング],[エリアルローリング]が溜め無しで発動可能"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyKick],
  movesName:"SA3 グランドシェイプキャノンボール",
  movesCondition:"",
  startup:10,
  active:"10-12",
  recovery:61,
  hit:"Down",
  block:-46,
  cancel:"×",
  tips:["1-12F 完全無敵","最低保障ダメージ50%","C/PCで数値が変動しない","必殺技キャンセル時のみ即時補正10%","HP25%以下で性能変化"],
  hitboxImage:"",
},{
  type:"スーパーアーツ",
  commands:[keyDown,keyDR,keyRight,keyDown,keyDR,keyRight,keyPlus,anyKick],
  movesName:"CA グランドシェイプキャノンボール",
  movesCondition:"",
  startup:10,
  active:"10-12",
  recovery:61,
  hit:"Down",
  block:-46,
  cancel:"×",
  tips:["1-12F 完全無敵","最低保障ダメージ50%","C/PCで数値が変動しない","必殺技キャンセル時のみ即時補正10%"],
  hitboxImage:"",
},{
  type:"投げ",
  commands:[keyNutral,keyOr,keyRight,keyPlus,lPunch,lKick],
  movesName:"ワイルドファング",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:23,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"投げ",
  commands:[keyLeft,keyPlus,lPunch,lKick],
  movesName:"ジャングルフリップ",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:23,
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},{
  type:"投げ",
  commands:[lPunch,lKick],
  movesName:"ワイルドバイツ",
  movesCondition:"",
  startup:5,
  active:"5-7",
  recovery:"",
  hit:"Down",
  block:"",
  cancel:"×",
  tips:[""],
  hitboxImage:"",
},]